copyright: Copyright &copy; 2021 - 2022 <a href="https://github.com/howie6879/weekly">howie.hu</a>.
markdown_extensions:
- toc:
    permalink: []
- admonition
- def_list
- codehilite
nav:
- ğŸŒˆ åˆ›åˆŠå¯„è¯­:
  - â¤ï¸: ./index.md
- ğŸ‚ 2021å¹´åˆŠ:
  - ç¬¬001æœŸ (08-16~08-20): ./2021/08-16~08-20.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬001æœŸï¼‰.md
  - ç¬¬002æœŸ (08-23~08-27): ./2021/08-23~08-27.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬002æœŸï¼‰.md
  - ç¬¬003æœŸ (08-30~09-03): ./2021/08-30~09-03.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬003æœŸï¼‰.md
  - ç¬¬004æœŸ (09-06~09-10): ./2021/09-06~09-10.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬004æœŸï¼‰.md
  - ç¬¬005æœŸ (09-12~09-17): ./2021/09-12~09-17.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬005æœŸï¼‰.md
  - ç¬¬006æœŸ (09-19~09-24): ./2021/09-19~09-24.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬006æœŸï¼‰.md
  - ç¬¬007æœŸ (09-27~10-03): ./2021/09-27~10-03.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬007æœŸï¼‰.md
  - ç¬¬008æœŸ (10-04~10-10): ./2021/10-04~10-10.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬008æœŸï¼‰.md
  - ç¬¬009æœŸ (10-11~10-17): ./2021/10-11~10-17.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬009æœŸï¼‰.md
  - ç¬¬010æœŸ (10-18~10-24): ./2021/10-18~10-24.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬010æœŸï¼‰.md
  - ç¬¬011æœŸ (10-25~10-31): ./2021/10-25~10-31.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬011æœŸï¼‰.md
  - ç¬¬012æœŸ (11-01~11-07): ./2021/11-01~11-07.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬012æœŸï¼‰.md
  - ç¬¬013æœŸ (11-08~11-14): ./2021/11-08~11-14.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬013æœŸï¼‰.md
  - ç¬¬014æœŸ (11-15~11-21): ./2021/11-15~11-21.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬014æœŸï¼‰.md
  - ç¬¬015æœŸ (11-22~11-28): ./2021/11-22~11-28.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬015æœŸï¼‰.md
  - ç¬¬016æœŸ (11-29~12-05): ./2021/11-29~12-05.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬016æœŸï¼‰.md
  - ç¬¬017æœŸ (12-06~12-12): ./2021/12-06~12-12.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬017æœŸï¼‰.md
  - ç¬¬018æœŸ (12-13~12-20): ./2021/12-13~12-20.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬018æœŸï¼‰.md
  - ç¬¬019æœŸ (12-21~12-25): ./2021/12-21~12-25.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬019æœŸï¼‰.md
  - ç¬¬020æœŸ (12-26~12-31): ./2021/12-26~12-31.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬020æœŸï¼‰.md
- ğŸ¯ 2022å¹´åˆŠ:
  - ç¬¬021æœŸ (01-01~01-09): ./2022/01-01~01-09.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬021æœŸï¼‰.md
  - ç¬¬022æœŸ (01-10~01-14): ./2022/01-10~01-14.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬022æœŸï¼‰.md
  - ç¬¬023æœŸ (01-17~01-22): ./2022/01-17~01-22.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬023æœŸï¼‰.md
  - ç¬¬024æœŸ (01-23~01-30): ./2022/01-23~01-30.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬024æœŸï¼‰.md
  - ç¬¬025æœŸ (01-31~02-05): ./2022/01-31~02-05.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬025æœŸï¼‰.md
  - ç¬¬026æœŸ (02-07~02-14): ./2022/02-07~02-14.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬026æœŸï¼‰.md
  - ç¬¬027æœŸ (02-15~02-20): ./2022/02-15~02-20.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬027æœŸï¼‰.md
  - ç¬¬028æœŸ (02-21~02-27): ./2022/02-21~02-27.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬028æœŸï¼‰.md
  - ç¬¬029æœŸ (02-28~03-05): ./2022/02-28~03-05.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬029æœŸï¼‰.md
  - ç¬¬030æœŸ (03-07~03-13): ./2022/03-07~03-13.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬030æœŸï¼‰.md
  - ç¬¬031æœŸ (03-14~03-20): ./2022/03-14~03-20.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬031æœŸï¼‰.md
  - ç¬¬032æœŸ (03-21~03-27): ./2022/03-21~03-27.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬032æœŸï¼‰.md
  - ç¬¬033æœŸ (03-28~04-03): ./2022/03-28~04-03.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬033æœŸï¼‰.md
  - ç¬¬034æœŸ (04-04~04-10): ./2022/04-04~04-10.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬034æœŸï¼‰.md
  - ç¬¬035æœŸ (04-11~04-16): ./2022/04-11~04-16.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬035æœŸï¼‰.md
  - ç¬¬036æœŸ (04-18~04-23): ./2022/04-18~04-23.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬036æœŸï¼‰.md
  - ç¬¬037æœŸ (04-25~05-01): ./2022/04-25~05-01.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬037æœŸï¼‰.md
  - ç¬¬038æœŸ (05-02~05-07): ./2022/05-02~05-07.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬038æœŸï¼‰.md
  - ç¬¬039æœŸ (05-09~05-15): ./2022/05-09~05-15.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬039æœŸï¼‰.md
  - ç¬¬040æœŸ (05-16~05-21): ./2022/05-16~05-21.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬040æœŸï¼‰.md
  - ç¬¬041æœŸ (05-23~05-28): ./2022/05-23~05-28.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬041æœŸï¼‰.md
  - ç¬¬042æœŸ (05-30~06-04): ./2022/05-30~06-04.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬042æœŸï¼‰.md
  - ç¬¬043æœŸ (06-06~06-11): ./2022/06-06~06-11.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬043æœŸï¼‰.md
  - ç¬¬044æœŸ (06-13~06-18): ./2022/06-13~06-18.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬044æœŸï¼‰.md
  - ç¬¬045æœŸ (06-20~06-25): ./2022/06-20~06-25.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬045æœŸï¼‰.md
  - ç¬¬046æœŸ (06-27~07-02): ./2022/06-27~07-02.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬046æœŸï¼‰.md
  - ç¬¬047æœŸ (07-04~07-10): ./2022/07-04~07-10.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬047æœŸï¼‰.md
- ğŸ€ ä»Šæ—¥æ¨è:
  - ğŸ€ ä»Šæ—¥æ¨è: ./recommend/index.md
- ğŸ”— RSSè®¢é˜…: ./rss/rss.xml
plugins:
- search:
    separator: '[\\s\\u200b\\-]'
- git-revision-date-localized
repo_name: howie6879/weekly
repo_url: https://github.com/howie6879/weekly
site_author: howie.hu
site_description: è€èƒ¡çš„ä¿¡æ¯å‘¨åˆŠï¼Œä¸ºæ‚¨å¸¦æ¥å„ç§å€¼å¾—æ”¶è—çš„è½¯ä»¶é¡¹ç›®ä»¥åŠèµ„æ–™ç½‘ç«™ >>> å¥‡æ–‡å…±æ¬£èµï¼Œç–‘ä¹‰ç›¸ä¸æ
site_name: è€èƒ¡çš„å‘¨åˆŠ
site_url: https://weekly.howie6879.cn/
theme:
  custom_dir: overrides
  favicon: ./statics/images/favicon.ico
  features:
  - content.code.annotate
  - navigation.expand
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  font:
    code: Roboto Mono
    text: Roboto
  language: zh
  logo: ./statics/images/howie.jpeg
  name: material
  palette:
  - accent: indigo
    primary: indigo
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - accent: black
    primary: black
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  search_index_only: true
use_directory_urls: false
