copyright: Copyright &copy; 2021 - 2023 <a href="https://github.com/howie6879/weekly">howie.hu</a>.
extra:
  social:
  - icon: fontawesome/brands/telegram
    link: https://t.me/howie_weekly
  - icon: fontawesome/brands/weixin
    link: https://images-1252557999.file.myqcloud.com/uPic/ETIbMe.jpg
  - icon: fontawesome/solid/blog
    link: https://www.howie6879.com
  - icon: fontawesome/brands/github-alt
    link: https://github.com/howie6879
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/howie6879
  - icon: fontawesome/solid/rss
    link: https://weekly.howie6879.com/rss/rss.xml
extra_css:
- statics/css/ui.css
- statics/css/custom.css
- https://gw.alipayobjects.com/os/k/font/lxgwwenkaiscreenr.css
extra_javascript:
- statics/js/custom.js
markdown_extensions:
- smarty
- toc:
    permalink: []
- admonition
- def_list
- codehilite
nav:
- ğŸŒˆ åˆ›åˆŠå¯„è¯­:
  - é¦–é¡µ: ./index.md
- ğŸ® 2021 ~ ğŸ² 2024:
  - ğŸ² 2024 å¹´åˆŠ:
    - ç¬¬173æœŸ (12-23~12-29): ./2024/12-23~12-29.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬173æœŸï¼‰.md
    - ç¬¬172æœŸ (12-16~12-22): ./2024/12-16~12-22.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬172æœŸï¼‰.md
    - ç¬¬171æœŸ (12-09~12-15): ./2024/12-09~12-15.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬171æœŸï¼‰.md
    - ç¬¬170æœŸ (11-25~12-08): ./2024/11-25~12-08.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬170æœŸï¼‰.md
    - ç¬¬169æœŸ (11-18~11-24): ./2024/11-18~11-24.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬169æœŸï¼‰.md
    - ç¬¬168æœŸ (11-11~11-17): ./2024/11-11~11-17.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬168æœŸï¼‰.md
    - ç¬¬167æœŸ (11-04~11-10): ./2024/11-04~11-10.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬167æœŸï¼‰.md
    - ç¬¬166æœŸ (10-28~11-03): ./2024/10-28~11-03.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬166æœŸï¼‰.md
    - ç¬¬165æœŸ (10-21~10-27): ./2024/10-21~10-27.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬165æœŸï¼‰.md
    - ç¬¬164æœŸ (10-14~10-20): ./2024/10-14~10-20.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬164æœŸï¼‰.md
    - ç¬¬163æœŸ (10-07~10-13): ./2024/10-07~10-13.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬163æœŸï¼‰.md
    - ç¬¬162æœŸ (09-30~10-06): ./2024/09-30~10-06.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬162æœŸï¼‰.md
    - ç¬¬161æœŸ (09-23~09-29): ./2024/09-23~09-29.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬161æœŸï¼‰.md
    - ç¬¬160æœŸ (09-17~09-22): ./2024/09-17~09-22.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬160æœŸï¼‰.md
    - ç¬¬159æœŸ (09-09~09-16): ./2024/09-09~09-16.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬159æœŸï¼‰.md
    - ç¬¬158æœŸ (09-02~09-07): ./2024/09-02~09-07.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬158æœŸï¼‰.md
    - ç¬¬157æœŸ (08-26~09-01): ./2024/08-26~09-01.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬157æœŸï¼‰.md
    - ç¬¬156æœŸ (08-19~08-25): ./2024/08-19~08-25.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬156æœŸï¼‰.md
    - ç¬¬155æœŸ (08-12~08-18): ./2024/08-12~08-18.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬155æœŸï¼‰.md
    - ç¬¬154æœŸ (08-05~08-11): ./2024/08-05~08-11.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬154æœŸï¼‰.md
    - ç¬¬153æœŸ (07-29~08-04): ./2024/07-29~08-04.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬153æœŸï¼‰.md
    - ç¬¬152æœŸ (07-22~07-28): ./2024/07-22~07-28.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬152æœŸï¼‰.md
    - ç¬¬151æœŸ (07-15~07-21): ./2024/07-15~07-21.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬151æœŸï¼‰.md
    - ç¬¬150æœŸ (07-08~07-14): ./2024/07-08~07-14.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬150æœŸï¼‰.md
    - ç¬¬149æœŸ (07-01~07-07): ./2024/07-01~07-07.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬149æœŸï¼‰.md
    - ç¬¬148æœŸ (06-24~06-30): ./2024/06-24~06-30.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬148æœŸï¼‰.md
    - ç¬¬147æœŸ (06-17~06-23): ./2024/06-17~06-23.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬147æœŸï¼‰.md
    - ç¬¬146æœŸ (06-11~06-16): ./2024/06-11~06-16.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬146æœŸï¼‰.md
    - ç¬¬145æœŸ (06-03~06-10): ./2024/06-03~06-10.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬145æœŸï¼‰.md
    - ç¬¬144æœŸ (05-27~06-02): ./2024/05-27~06-02.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬144æœŸï¼‰.md
    - ç¬¬143æœŸ (05-20~05-26): ./2024/05-20~05-26.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬143æœŸï¼‰.md
    - ç¬¬142æœŸ (05-13~05-19): ./2024/05-13~05-19.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬142æœŸï¼‰.md
    - ç¬¬141æœŸ (05-06~05-12): ./2024/05-06~05-12.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬141æœŸï¼‰.md
    - ç¬¬140æœŸ (04-29~05-05): ./2024/04-29~05-05.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬140æœŸï¼‰.md
    - ç¬¬139æœŸ (04-22~04-28): ./2024/04-22~04-28.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬139æœŸï¼‰.md
    - ç¬¬138æœŸ (04-15~04-21): ./2024/04-15~04-21.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬138æœŸï¼‰.md
    - ç¬¬137æœŸ (04-08~04-14): ./2024/04-08~04-14.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬137æœŸï¼‰.md
    - ç¬¬136æœŸ (04-01~04-07): ./2024/04-01~04-07.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬136æœŸï¼‰.md
    - ç¬¬135æœŸ (03-25~03-31): ./2024/03-25~03-31.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬135æœŸï¼‰.md
    - ç¬¬134æœŸ (03-18~03-24): ./2024/03-18~03-24.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬134æœŸï¼‰.md
    - ç¬¬133æœŸ (03-11~03-17): ./2024/03-11~03-17.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬133æœŸï¼‰.md
    - ç¬¬132æœŸ (03-04~03-10): ./2024/03-04~03-10.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬132æœŸï¼‰.md
    - ç¬¬131æœŸ (02-26~03-03): ./2024/02-26~03-03.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬131æœŸï¼‰.md
    - ç¬¬130æœŸ (02-19~02-25): ./2024/02-19~02-25.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬130æœŸï¼‰.md
    - ç¬¬129æœŸ (02-12~02-18): ./2024/02-12~02-18.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬129æœŸï¼‰.md
    - ç¬¬128æœŸ (02-05~02-11): ./2024/02-05~02-11.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬128æœŸï¼‰.md
    - ç¬¬127æœŸ (01-29~02-04): ./2024/01-29~02-04.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬127æœŸï¼‰.md
    - ç¬¬126æœŸ (01-22~01-28): ./2024/01-22~01-28.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬126æœŸï¼‰.md
    - ç¬¬125æœŸ (01-15~01-21): ./2024/01-15~01-21.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬125æœŸï¼‰.md
    - ç¬¬124æœŸ (01-08~01-14): ./2024/01-08~01-14.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬124æœŸï¼‰.md
    - ç¬¬123æœŸ (01-01~01-07): ./2024/01-01~01-07.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬123æœŸï¼‰.md
  - ğŸ° 2023 å¹´åˆŠ:
    - ç¬¬122æœŸ (12-25~12-31): ./2023/12-25~12-31.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬122æœŸï¼‰.md
    - ç¬¬121æœŸ (12-18~12-24): ./2023/12-18~12-24.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬121æœŸï¼‰.md
    - ç¬¬120æœŸ (12-11~12-17): ./2023/12-11~12-17.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬120æœŸï¼‰.md
    - ç¬¬119æœŸ (12-04~12-09): ./2023/12-04~12-09.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬119æœŸï¼‰.md
    - ç¬¬118æœŸ (11-27~12-03): ./2023/11-27~12-03.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬118æœŸï¼‰.md
    - ç¬¬117æœŸ (11-20~11-26): ./2023/11-20~11-26.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬117æœŸï¼‰.md
    - ç¬¬116æœŸ (11-13~11-19): ./2023/11-13~11-19.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬116æœŸï¼‰.md
    - ç¬¬115æœŸ (11-06~11-11): ./2023/11-06~11-11.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬115æœŸï¼‰.md
    - ç¬¬114æœŸ (10-31~11-05): ./2023/10-31~11-05.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬114æœŸï¼‰.md
    - ç¬¬113æœŸ (10-23~10-29): ./2023/10-23~10-29.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬113æœŸï¼‰.md
    - ç¬¬112æœŸ (10-16~10-22): ./2023/10-16~10-22.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬112æœŸï¼‰.md
    - ç¬¬111æœŸ (10-09~10-15): ./2023/10-09~10-15.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬111æœŸï¼‰.md
    - ç¬¬110æœŸ (09-25~10-07): ./2023/09-25~10-07.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬110æœŸï¼‰.md
    - ç¬¬109æœŸ (09-18~09-24): ./2023/09-18~09-24.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬109æœŸï¼‰.md
    - ç¬¬108æœŸ (09-11~09-17): ./2023/09-11~09-17.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬108æœŸï¼‰.md
    - ç¬¬107æœŸ (09-04~09-10): ./2023/09-04~09-10.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬107æœŸï¼‰.md
    - ç¬¬106æœŸ (08-28~09-03): ./2023/08-28~09-03.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬106æœŸï¼‰.md
    - ç¬¬105æœŸ (08-21~08-27): ./2023/08-21~08-27.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬105æœŸï¼‰.md
    - ç¬¬104æœŸ (08-14~08-20): ./2023/08-14~08-20.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬104æœŸï¼‰.md
    - ç¬¬103æœŸ (08-07~08-13): ./2023/08-07~08-13.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬103æœŸï¼‰.md
    - ç¬¬102æœŸ (08-01~08-07): ./2023/08-01~08-07.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬102æœŸï¼‰.md
    - ç¬¬101æœŸ (07-24~07-30): ./2023/07-24~07-30.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬101æœŸï¼‰.md
    - ç¬¬100æœŸ (07-17~07-23): ./2023/07-17~07-23.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬100æœŸï¼‰.md
    - ç¬¬099æœŸ (07-10~07-16): ./2023/07-10~07-16.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬099æœŸï¼‰.md
    - ç¬¬098æœŸ (07-03~07-07): ./2023/07-03~07-07.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬098æœŸï¼‰.md
    - ç¬¬097æœŸ (06-25~07-01): ./2023/06-25~07-01.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬097æœŸï¼‰.md
    - ç¬¬096æœŸ (06-19~06-24): ./2023/06-19~06-24.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬096æœŸï¼‰.md
    - ç¬¬095æœŸ (06-12~06-17): ./2023/06-12~06-17.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬095æœŸï¼‰.md
    - ç¬¬094æœŸ (06-05~06-11): ./2023/06-05~06-11.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬094æœŸï¼‰.md
    - ç¬¬093æœŸ (05-29~06-04): ./2023/05-29~06-04.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬093æœŸï¼‰.md
    - ç¬¬092æœŸ (05-22~05-28): ./2023/05-22~05-28.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬092æœŸï¼‰.md
    - ç¬¬091æœŸ (05-15~05-20): ./2023/05-15~05-20.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬091æœŸï¼‰.md
    - ç¬¬090æœŸ (05-01~05-13): ./2023/05-01~05-13.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬090æœŸï¼‰.md
    - ç¬¬089æœŸ (04-24~04-30): ./2023/04-24~04-30.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬089æœŸï¼‰.md
    - ç¬¬088æœŸ (04-17~04-22): ./2023/04-17~04-22.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬088æœŸï¼‰.md
    - ç¬¬087æœŸ (04-10~04-15): ./2023/04-10~04-15.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬087æœŸï¼‰.md
    - ç¬¬086æœŸ (04-03~04-08): ./2023/04-03~04-08.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬086æœŸï¼‰.md
    - ç¬¬085æœŸ (03-27~04-01): ./2023/03-27~04-01.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬085æœŸï¼‰.md
    - ç¬¬084æœŸ (03-20~03-25): ./2023/03-20~03-25.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬084æœŸï¼‰.md
    - ç¬¬083æœŸ (03-13~03-19): ./2023/03-13~03-19.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬083æœŸï¼‰.md
    - ç¬¬082æœŸ (03-06~03-11): ./2023/03-06~03-11.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬082æœŸï¼‰.md
    - ç¬¬081æœŸ (02-27~03-05): ./2023/02-27~03-05.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬081æœŸï¼‰.md
    - ç¬¬080æœŸ (02-20~02-25): ./2023/02-20~02-25.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬080æœŸï¼‰.md
    - ç¬¬079æœŸ (02-13~02-18): ./2023/02-13~02-18.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬079æœŸï¼‰.md
    - ç¬¬078æœŸ (02-06~02-12): ./2023/02-06~02-12.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬078æœŸï¼‰.md
    - ç¬¬077æœŸ (01-31~02-05): ./2023/01-31~02-05.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬077æœŸï¼‰.md
    - ç¬¬076æœŸ (01-23~01-28): ./2023/01-23~01-28.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬076æœŸï¼‰.md
    - ç¬¬075æœŸ (01-16~01-21): ./2023/01-16~01-21.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬075æœŸï¼‰.md
    - ç¬¬074æœŸ (01-09~01-14): ./2023/01-09~01-14.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬074æœŸï¼‰.md
    - ç¬¬073æœŸ (01-02~01-07): ./2023/01-02~01-07.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬073æœŸï¼‰.md
  - ğŸ¯ 2022 å¹´åˆŠ:
    - ç¬¬072æœŸ (12-26~12-31): ./2022/12-26~12-31.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬072æœŸï¼‰.md
    - ç¬¬071æœŸ (12-19~12-24): ./2022/12-19~12-24.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬071æœŸï¼‰.md
    - ç¬¬070æœŸ (12-12~12-18): ./2022/12-12~12-18.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬070æœŸï¼‰.md
    - ç¬¬069æœŸ (12-05~12-10): ./2022/12-05~12-10.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬069æœŸï¼‰.md
    - ç¬¬068æœŸ (11-28~12-04): ./2022/11-28~12-04.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬068æœŸï¼‰.md
    - ç¬¬067æœŸ (11-21~11-27): ./2022/11-21~11-27.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬067æœŸï¼‰.md
    - ç¬¬066æœŸ (11-14~11-20): ./2022/11-14~11-20.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬066æœŸï¼‰.md
    - ç¬¬065æœŸ (11-07~11-13): ./2022/11-07~11-13.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬065æœŸï¼‰.md
    - ç¬¬064æœŸ (10-31~11-06): ./2022/10-31~11-06.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬064æœŸï¼‰.md
    - ç¬¬063æœŸ (10-24~10-30): ./2022/10-24~10-30.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬063æœŸï¼‰.md
    - ç¬¬062æœŸ (10-17~10-23): ./2022/10-17~10-23.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬062æœŸï¼‰.md
    - ç¬¬061æœŸ (10-10~10-16): ./2022/10-10~10-16.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬061æœŸï¼‰.md
    - ç¬¬060æœŸ (10-03~10-09): ./2022/10-03~10-09.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬060æœŸï¼‰.md
    - ç¬¬059æœŸ (09-26~09-30): ./2022/09-26~09-30.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬059æœŸï¼‰.md
    - ç¬¬058æœŸ (09-19~09-24): ./2022/09-19~09-24.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬058æœŸï¼‰.md
    - ç¬¬057æœŸ (09-12~09-18): ./2022/09-12~09-18.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬057æœŸï¼‰.md
    - ç¬¬056æœŸ (09-05~09-11): ./2022/09-05~09-11.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬056æœŸï¼‰.md
    - ç¬¬055æœŸ (08-29~09-04): ./2022/08-29~09-04.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬055æœŸï¼‰.md
    - ç¬¬054æœŸ (08-22~08-28): ./2022/08-22~08-28.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬054æœŸï¼‰.md
    - ç¬¬053æœŸ (08-15~08-21): ./2022/08-15~08-21.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬053æœŸï¼‰.md
    - ç¬¬052æœŸ (08-07~08-14): ./2022/08-07~08-14.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬052æœŸï¼‰.md
    - ç¬¬051æœŸ (08-01~08-07): ./2022/08-01~08-07.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬051æœŸï¼‰.md
    - ç¬¬050æœŸ (07-25~07-31): ./2022/07-25~07-31.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬050æœŸï¼‰.md
    - ç¬¬049æœŸ (07-18~07-24): ./2022/07-18~07-24.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬049æœŸï¼‰.md
    - ç¬¬048æœŸ (07-11~07-17): ./2022/07-11~07-17.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬048æœŸï¼‰.md
    - ç¬¬047æœŸ (07-04~07-10): ./2022/07-04~07-10.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬047æœŸï¼‰.md
    - ç¬¬046æœŸ (06-27~07-02): ./2022/06-27~07-02.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬046æœŸï¼‰.md
    - ç¬¬045æœŸ (06-20~06-25): ./2022/06-20~06-25.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬045æœŸï¼‰.md
    - ç¬¬044æœŸ (06-13~06-18): ./2022/06-13~06-18.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬044æœŸï¼‰.md
    - ç¬¬043æœŸ (06-06~06-11): ./2022/06-06~06-11.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬043æœŸï¼‰.md
    - ç¬¬042æœŸ (05-30~06-04): ./2022/05-30~06-04.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬042æœŸï¼‰.md
    - ç¬¬041æœŸ (05-23~05-28): ./2022/05-23~05-28.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬041æœŸï¼‰.md
    - ç¬¬040æœŸ (05-16~05-21): ./2022/05-16~05-21.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬040æœŸï¼‰.md
    - ç¬¬039æœŸ (05-09~05-15): ./2022/05-09~05-15.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬039æœŸï¼‰.md
    - ç¬¬038æœŸ (05-02~05-07): ./2022/05-02~05-07.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬038æœŸï¼‰.md
    - ç¬¬037æœŸ (04-25~05-01): ./2022/04-25~05-01.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬037æœŸï¼‰.md
    - ç¬¬036æœŸ (04-18~04-23): ./2022/04-18~04-23.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬036æœŸï¼‰.md
    - ç¬¬035æœŸ (04-11~04-16): ./2022/04-11~04-16.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬035æœŸï¼‰.md
    - ç¬¬034æœŸ (04-04~04-10): ./2022/04-04~04-10.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬034æœŸï¼‰.md
    - ç¬¬033æœŸ (03-28~04-03): ./2022/03-28~04-03.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬033æœŸï¼‰.md
    - ç¬¬032æœŸ (03-21~03-27): ./2022/03-21~03-27.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬032æœŸï¼‰.md
    - ç¬¬031æœŸ (03-14~03-20): ./2022/03-14~03-20.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬031æœŸï¼‰.md
    - ç¬¬030æœŸ (03-07~03-13): ./2022/03-07~03-13.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬030æœŸï¼‰.md
    - ç¬¬029æœŸ (02-28~03-05): ./2022/02-28~03-05.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬029æœŸï¼‰.md
    - ç¬¬028æœŸ (02-21~02-27): ./2022/02-21~02-27.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬028æœŸï¼‰.md
    - ç¬¬027æœŸ (02-15~02-20): ./2022/02-15~02-20.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬027æœŸï¼‰.md
    - ç¬¬026æœŸ (02-07~02-14): ./2022/02-07~02-14.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬026æœŸï¼‰.md
    - ç¬¬025æœŸ (01-31~02-05): ./2022/01-31~02-05.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬025æœŸï¼‰.md
    - ç¬¬024æœŸ (01-23~01-30): ./2022/01-23~01-30.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬024æœŸï¼‰.md
    - ç¬¬023æœŸ (01-17~01-22): ./2022/01-17~01-22.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬023æœŸï¼‰.md
    - ç¬¬022æœŸ (01-10~01-14): ./2022/01-10~01-14.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬022æœŸï¼‰.md
    - ç¬¬021æœŸ (01-01~01-09): ./2022/01-01~01-09.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬021æœŸï¼‰.md
  - ğŸ® 2021 å¹´åˆŠ:
    - ç¬¬020æœŸ (12-26~12-31): ./2021/12-26~12-31.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬020æœŸï¼‰.md
    - ç¬¬019æœŸ (12-21~12-25): ./2021/12-21~12-25.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬019æœŸï¼‰.md
    - ç¬¬018æœŸ (12-13~12-20): ./2021/12-13~12-20.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬018æœŸï¼‰.md
    - ç¬¬017æœŸ (12-06~12-12): ./2021/12-06~12-12.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬017æœŸï¼‰.md
    - ç¬¬016æœŸ (11-29~12-05): ./2021/11-29~12-05.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬016æœŸï¼‰.md
    - ç¬¬015æœŸ (11-22~11-28): ./2021/11-22~11-28.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬015æœŸï¼‰.md
    - ç¬¬014æœŸ (11-15~11-21): ./2021/11-15~11-21.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬014æœŸï¼‰.md
    - ç¬¬013æœŸ (11-08~11-14): ./2021/11-08~11-14.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬013æœŸï¼‰.md
    - ç¬¬012æœŸ (11-01~11-07): ./2021/11-01~11-07.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬012æœŸï¼‰.md
    - ç¬¬011æœŸ (10-25~10-31): ./2021/10-25~10-31.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬011æœŸï¼‰.md
    - ç¬¬010æœŸ (10-18~10-24): ./2021/10-18~10-24.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬010æœŸï¼‰.md
    - ç¬¬009æœŸ (10-11~10-17): ./2021/10-11~10-17.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬009æœŸï¼‰.md
    - ç¬¬008æœŸ (10-04~10-10): ./2021/10-04~10-10.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬008æœŸï¼‰.md
    - ç¬¬007æœŸ (09-27~10-03): ./2021/09-27~10-03.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬007æœŸï¼‰.md
    - ç¬¬006æœŸ (09-19~09-24): ./2021/09-19~09-24.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬006æœŸï¼‰.md
    - ç¬¬005æœŸ (09-12~09-17): ./2021/09-12~09-17.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬005æœŸï¼‰.md
    - ç¬¬004æœŸ (09-06~09-10): ./2021/09-06~09-10.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬004æœŸï¼‰.md
    - ç¬¬003æœŸ (08-30~09-03): ./2021/08-30~09-03.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬003æœŸï¼‰.md
    - ç¬¬002æœŸ (08-23~08-27): ./2021/08-23~08-27.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬002æœŸï¼‰.md
    - ç¬¬001æœŸ (08-16~08-20): ./2021/08-16~08-20.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬001æœŸï¼‰.md
- ğŸ 2025 å¹´åˆŠ:
  - ç¬¬174æœŸ (01-01~01-05): ./2025/01-01~01-05.è€èƒ¡çš„å‘¨åˆŠï¼ˆç¬¬174æœŸï¼‰.md
- ğŸ€ ä»Šæ—¥æ¨è:
  - ğŸ€ ä»Šæ—¥æ¨è: ./recommend/index.md
- ğŸ’» è½¯ä»¶æ¨è:
  - ğŸ æˆ‘çš„ macOS å¸¸ç”¨è½¯ä»¶: ./soft/mac.md
  - ğŸ¤– ChatGPT å¼€æºåº”ç”¨æœˆåº¦æ’å: ./soft/chatgpt.md
- ğŸ‘ FRE123: https://www.fre123.com?ref=howie6879_weekly
- ğŸ”— RSSè®¢é˜…: ./rss/rss.xml
plugins:
- search:
    separator: '[\s\u200b\-]'
- open-in-new-tab
- git-revision-date-localized
repo_name: howie6879/weekly
repo_url: https://github.com/howie6879/weekly
site_author: howie.hu
site_description: è€èƒ¡çš„ä¿¡æ¯å‘¨åˆŠï¼Œä¸ºæ‚¨å¸¦æ¥å„ç§å€¼å¾—æ”¶è—çš„è½¯ä»¶é¡¹ç›®ä»¥åŠèµ„æ–™ç½‘ç«™ >>> å¥‡æ–‡å…±æ¬£èµï¼Œç–‘ä¹‰ç›¸ä¸æ
site_name: è€èƒ¡çš„å‘¨åˆŠ
site_url: https://weekly.howie6879.com/
theme:
  custom_dir: overrides
  favicon: ./statics/images/favicon.ico
  features:
  - content.code.annotate
  - navigation.expand
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  font:
    code: Roboto Mono
    text: Roboto
  language: zh
  logo: ./statics/images/howie.jpeg
  name: material
  palette:
  - accent: indigo
    primary: white
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - accent: black
    primary: black
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  search_index_only: true
use_directory_urls: false
