site_name: è€èƒ¡çš„å‘¨åˆŠ
site_url: https://weekly.howie6879.cn/
site_description: 'è€èƒ¡çš„ä¿¡æ¯å‘¨åˆŠ >>> å¥‡æ–‡å…±æ¬£èµï¼Œç–‘ä¹‰ç›¸ä¸æ'
site_author: howie.hu

repo_url: https://github.com/howie6879/weekly
repo_name: 'howie6879/weekly'

copyright: Copyright &copy; 2021 - 2021 <a href="https://github.com/howie6879/weekly">howie.hu</a>.

theme:
  name: 'material'
  search_index_only: true
  language: 'zh'
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: './statics/images/howie.jpeg'
  favicon: './statics/images/favicon.ico'

use_directory_urls: false

nav:
  - â¤ï¸ åˆ›åˆŠå¯„è¯­: 
    - â¤ï¸ åˆ›åˆŠå¯„è¯­: ./index.md
    - ğŸ§‘ğŸ»â€ğŸ’» å…³äºæˆ‘: ./home/about.md
  - ğŸ‘€ 2021å¹´åˆŠ:
    - ç¬¬001æœŸ (08-16~08-20): ./2021/08-16~08-20.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬001æœŸï¼‰.md
    - ç¬¬002æœŸ (08-23~08-27): ./2021/08-23~08-27.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬002æœŸï¼‰.md
    - ç¬¬003æœŸ (08-30~09-03): ./2021/08-30~09-03.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬003æœŸï¼‰.md
    - ç¬¬004æœŸ (09-06~09-10): ./2021/09-06~09-10.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬004æœŸï¼‰.md
    - ç¬¬005æœŸ (09-12~09-17): ./2021/09-12~09-17.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬005æœŸï¼‰.md
    - ç¬¬006æœŸ (09-19~09-24): ./2021/09-19~09-24.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬006æœŸï¼‰.md
    - ç¬¬007æœŸ (09-27~10-03): ./2021/09-27~10-03.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬007æœŸï¼‰.md
    - ç¬¬008æœŸ (10-04~10-10): ./2021/10-04~10-10.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬008æœŸï¼‰.md
    - ç¬¬009æœŸ (10-11~10-17): ./2021/10-11~10-17.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬009æœŸï¼‰.md
    - ç¬¬010æœŸ (10-18~10-24): ./2021/10-18~10-24.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬010æœŸï¼‰.md
    - ç¬¬011æœŸ (10-25~10-31): ./2021/10-25~10-31.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬011æœŸï¼‰.md
  - ğŸ‰ éšæœºæ¼«æ­¥: 
    - ä»Šæ—¥æ¨è: ./recommend/today.md
    - æ¼«æ­¥2021: ./recommend/random_2021.md
  
plugins:
    - search

extra:
  search:
    language: 'jp'

markdown_extensions:
  - toc:
      permalink: []
  - admonition
  - def_list
  - codehilite