copyright: Copyright &copy; 2021 - 2021 <a href="https://github.com/howie6879/weekly">howie.hu</a>.
extra:
  disqus: weekly-howie6879
  search:
    language: jp
markdown_extensions:
- toc:
    permalink: []
- admonition
- def_list
- codehilite
nav:
- â¤ï¸ åˆ›åˆŠå¯„è¯­:
  - â¤ï¸ åˆ›åˆŠå¯„è¯­: ./index.md
  - ğŸ§‘ğŸ» å…³äºæˆ‘: ./home/about.md
- ğŸ‘€ 2021å¹´åˆŠ:
  - ç¬¬001æœŸ (08-16~08-20): ./2021/08-16~08-20.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬001æœŸï¼‰.md
  - ç¬¬002æœŸ (08-23~08-27): ./2021/08-23~08-27.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬002æœŸï¼‰.md
  - ç¬¬003æœŸ (08-30~09-03): ./2021/08-30~09-03.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬003æœŸï¼‰.md
  - ç¬¬004æœŸ (09-06~09-10): ./2021/09-06~09-10.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬004æœŸï¼‰.md
  - ç¬¬005æœŸ (09-12~09-17): ./2021/09-12~09-17.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬005æœŸï¼‰.md
  - ç¬¬006æœŸ (09-19~09-24): ./2021/09-19~09-24.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬006æœŸï¼‰.md
  - ç¬¬007æœŸ (09-27~10-03): ./2021/09-27~10-03.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬007æœŸï¼‰.md
  - ç¬¬008æœŸ (10-04~10-10): ./2021/10-04~10-10.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬008æœŸï¼‰.md
  - ç¬¬009æœŸ (10-11~10-17): ./2021/10-11~10-17.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬009æœŸï¼‰.md
  - ç¬¬010æœŸ (10-18~10-24): ./2021/10-18~10-24.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬010æœŸï¼‰.md
  - ç¬¬011æœŸ (10-25~10-31): ./2021/10-25~10-31.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬011æœŸï¼‰.md
  - ç¬¬012æœŸ (11-01~11-07): ./2021/11-01~11-07.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬012æœŸï¼‰.md
  - ç¬¬013æœŸ (11-08~11-14): ./2021/11-08~11-14.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬013æœŸï¼‰.md
  - ç¬¬014æœŸ (11-15~11-21): ./2021/11-15~11-21.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬014æœŸï¼‰.md
  - ç¬¬015æœŸ (11-22~11-28): ./2021/11-22~11-28.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬015æœŸï¼‰.md
  - ç¬¬016æœŸ (11-29~12-05): ./2021/11-29~12-05.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬016æœŸï¼‰.md
  - ç¬¬017æœŸ (12-06~12-12): ./2021/12-06~12-12.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬017æœŸï¼‰.md
  - ç¬¬018æœŸ (12-13~12-20): ./2021/12-13~12-20.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬018æœŸï¼‰.md
  - ç¬¬019æœŸ (12-21~12-25): ./2021/12-21~12-25.æˆ‘çš„å‘¨åˆŠï¼ˆç¬¬019æœŸï¼‰.md
- ğŸ‰ éšæœºæ¼«æ­¥:
  - ä»Šæ—¥æ¨è: ./recommend/today.md
  - æ¼«æ­¥2021: ./recommend/random_2021.md
- ğŸ”— RSSè®¢é˜…: https://weekly.howie6879.cn/feed_rss_created.xml
plugins:
- rss:
    abstract_chars_count: -1
- search
- git-revision-date-localized
repo_name: howie6879/weekly
repo_url: https://github.com/howie6879/weekly
site_author: howie.hu
site_description: è€èƒ¡çš„ä¿¡æ¯å‘¨åˆŠï¼Œä¸ºæ‚¨å¸¦æ¥å„ç§å€¼å¾—æ”¶è—çš„è½¯ä»¶é¡¹ç›®ä»¥åŠèµ„æ–™ç½‘ç«™ >>> å¥‡æ–‡å…±æ¬£èµï¼Œç–‘ä¹‰ç›¸ä¸æ
site_name: è€èƒ¡çš„å‘¨åˆŠ
site_url: https://weekly.howie6879.cn/
theme:
  favicon: ./statics/images/favicon.ico
  features:
  - content.code.annotate
  - navigation.expand
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  font:
    code: Roboto Mono
    text: Roboto
  language: zh
  logo: ./statics/images/howie.jpeg
  name: material
  palette:
  - accent: indigo
    primary: indigo
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - accent: black
    primary: black
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  search_index_only: true
use_directory_urls: false
